# Generated by Django 3.1.2 on 2020-10-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201010_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='published_date',
        ),
    ]
