# Generated by Django 2.2.16 on 2020-10-25 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_useraccount_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='password',
            new_name='Password',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
