# Generated by Django 2.2.16 on 2020-10-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201025_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Repeatpassword',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='useraccount2',
            name='Repeatpassword',
            field=models.CharField(default='', max_length=200),
        ),
    ]
