# Generated by Django 3.1.4 on 2021-01-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201025_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='useraccount2',
            old_name='Password',
            new_name='password',
        ),
    ]
