# Generated by Django 3.1.4 on 2021-01-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210103_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='useraccount2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
