# Generated by Django 3.1.4 on 2021-01-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
