# Generated by Django 3.1.4 on 2021-01-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210116_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='back_order',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='pre_order',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
