# Generated by Django 3.1.4 on 2021-01-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PS5', 'PlayStation 5'), ('XS', 'Xbox Series X/S'), ('PS', 'PlayStation'), ('MS', 'Microsoft'), ('NT', 'Nintendo')], default='Consoles', max_length=3),
            preserve_default=False,
        ),
    ]
