# Generated by Django 3.1.5 on 2021-02-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='product',
        ),
    ]
