# Generated by Django 3.1.5 on 2021-02-24 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_auto_20210224_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='Customer',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
