# Generated by Django 3.1.5 on 2021-03-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_shippingaddress_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postcode',
            new_name='zipcode',
        ),
    ]
