# Generated by Django 3.1.5 on 2021-03-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='name',
        ),
    ]
