# Generated by Django 3.1.5 on 2021-03-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_favorites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
