# Generated by Django 3.1.5 on 2021-03-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_favorites_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='name',
        ),
    ]
