# Generated by Django 3.1.5 on 2021-03-22 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_remove_favorites_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.AddField(
            model_name='favorites',
            name='back_order',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='category',
            field=models.CharField(choices=[('PS5', 'PlayStation 5'), ('XS', 'Xbox Series X/S'), ('PS', 'PlayStation'), ('MS', 'Microsoft'), ('NT', 'Nintendo')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='favorites',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='favorites',
            name='pre_order',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='favorites',
            name='stock',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
