# Generated by Django 3.1.5 on 2021-04-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
